eureka:
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka/

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yemengdeliyang/springcloud1
          username: yemendgeliyang
          password: 19940219liyang
